spring.application.name=HCM-K24-CNTT1-NguyenDaiPhat-002

#datasource
spring.datasource.url=jdbc://localhost:3306/gamingGeardb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
